services:
  tarantula:
    container_name: tarantula
    build:
      context: .
      dockerfile: Dockerfile
    image: tarantula:latest
    stdin_open: true
    tty: true
    volumes:
      - ./:/tarantula/
    ports:
      - "8080:8080"
      - "8090:8090"
    command: cargo run --release